### ISSUE TITLE
Error while loading rule 'react/no-multi-comp': Can't add property react, object is not extensible

### ISSUE THREAD

**Issue by leoderbois** [putaindecode/putaindecode.io#538]
Yop,
Because I'm a good beta tester : 
I can't make a `npm start`, I'have got this error with a new clone of your code or my fork : 

```
[7:53:24 PM] [webpack] ✓ build is now VALID
webpack built 1e9eb162f745a697ccfb in 1022ms
Hash: 1e9eb162f745a697ccfb
Version: webpack 1.12.6
Time: 1022ms
chunk    {0} statinamic-client.js (statinamic-client) 7.64 kB [rendered]

ERROR in ./scripts/index-client.js
Module build failed: TypeError: Error while loading rule 'react/no-multi-comp': Can't add property react, object is not extensible
    at Function.componentRule (/Users/leo/Temporary/putaindecode.io/node_modules/eslint-plugin-react/lib/util/Components.js:111:17)
    at /Users/leo/Temporary/putaindecode.io/node_modules/eslint/lib/eslint.js:692:28
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/leo/Temporary/putaindecode.io/node_modules/eslint/lib/eslint.js:671:16)
    at processText (/Users/leo/Temporary/putaindecode.io/node_modules/eslint/lib/cli-engine.js:230:27)
    at CLIEngine.executeOnText (/Users/leo/Temporary/putaindecode.io/node_modules/eslint/lib/cli-engine.js:686:26)
    at lint (/Users/leo/Temporary/putaindecode.io/node_modules/eslint-loader/index.js:26:20)
    at Object.module.exports (/Users/leo/Temporary/putaindecode.io/node_modules/eslint-loader/index.js:127:7)
 @ multi statinamic-client
```

Good luck ! 

It can be a good idea for you to get a VM with a **nude** install of the OS to retry all process on your side.

**Comment by magsout** [comment]
OK I can reproduce your error.

**Comment by MoOx** [comment]
Weird, because it's ok on Travis-CI.
Since it looks like an eslint issue, it might be related to a recent update (1.10.0 just came out).
What are your version of eslint guys?

**Comment by MoOx** [comment]
So just rollback to eslint 1.9.x for now => https://github.com/yannickcr/eslint-plugin-react/issues/323

**Comment by magsout** [comment]
yes due to eslint. Works now
