### ISSUE TITLE
BUG!!!

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.io#88]
```
Initializing
Command-line options: --verbose, --base=/Users/kud/Projects/_putaindecode/website

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Reading /Users/kud/Projects/_putaindecode/website/node_modules/happyplan/happyplan.json...OK
Parsing /Users/kud/Projects/_putaindecode/website/node_modules/happyplan/happyplan.json...OK
Environnment is dev
CWD is /Users/kud/Projects/_putaindecode/website
happyplan wd is /Users/kud/Projects/_putaindecode/website/node_modules/happyplan
Reading /Users/kud/Projects/_putaindecode/website/node_modules/happyplan/package.json...OK
Parsing /Users/kud/Projects/_putaindecode/website/node_modules/happyplan/package.json...OK
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module '../function/makeIterator_'
>>     at Function.Module._resolveFilename (module.js:338:15)
>>     at Function.Module._load (module.js:280:25)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/Users/kud/Projects/_putaindecode/website/node_modules/bower/node_modules/mout/array/collect.js:2:20)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)

Running tasks: happyplan:default
Warning: Task "happyplan:default" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by dangry** [comment]
Thanks @MoOx your answer solved my issue.
